### ISSUE TITLE
Сотрудничество

### ISSUE THREAD

**Issue by Azario16** [bbogush/web_screen#2]
Еще раз привет!
Я сам веб разработчик но появилась задача сделать андроид приложение скриншеринга экрана телефона для более удобного саппорта пользователей с андроидом, как рассматриваешь не длительные созвоны чтобы помочь в реализации на основе твоего приложения, само собой не бесплатно

**Comment by bbogush** [comment]
Привет! 
Спасибо за интерес к проекту! К сожалению, нет времени.
