### ISSUE TITLE
when I open 8080 port on router I can't see phone screen but buttons are still working

### ISSUE THREAD

**Issue by diegoacs0** [bbogush/web_screen#3]
Hi Mr bbogush!

Can you tell me which ports are being used on this application? 
I have been trying to find them so I can open these in my router firewall and share with all internet, but no success at all. Just port 8080 atm.

**Comment by bbogush** [comment]
Hi,
The video connection (WebRTC) uses dynamic ports so currently it is not possible to use it from internet, only in LAN.

**Comment by diegoacs0** [comment]
So bad... Is there any other alternative for streaming phone screen out of lan, but self-hosting this?

**Comment by bbogush** [comment]
If you just need screen share, without remote control, you can try https://github.com/dkrivoruchko/ScreenStream, it uses plain http and jpeg images for communication.
