### ISSUE TITLE
HTTPS certificate invalid

### ISSUE THREAD

**Issue by kazmer1998** [bbogush/web_screen#4]
I got this problem when I open the URL in browser:
NET::ERR_CERT_AUTHORITY_INVALID
But the certificaion datas seems right. What is the problem?
![kép](https://user-images.githubusercontent.com/49659474/192583521-d53bd415-2bde-4aa7-b402-978530e3a1e8.png)
Can you solve this?

**Comment by bbogush** [comment]
This error due to self-signed certificate. It cannot be solved. You need to skip this warning in the browser.

**Comment by kazmer1998** [comment]
Thanks!
Can I access the webpage through http?
Can you make a selector whether I would like to use HTTP or HTTPS?

**Comment by bbogush** [comment]
HTTP is not supported. Unfortunately I don't have time to add selector in near future.

**Comment by kazmer1998** [comment]
Understandable!
May I ask for an older release with only HTTP? (before v1.1.0)

**Comment by bbogush** [comment]
Sorry, I don't have this build. If you need HTTP you can try another app - https://github.com/dkrivoruchko/ScreenStream
